updated workflow error handling 6

diff --git a/.github/workflows/buildandDeploySandbox.yaml b/.github/workflows/buildandDeploySandbox.yaml
--- a/.github/workflows/buildandDeploySandbox.yaml
+++ b/.github/workflows/buildandDeploySandbox.yaml
@@ -151,3 +151,15 @@ jobs:
                     }
                 }
             }')
+           # Extract HTTP status code
+          status_code=$(echo "$responseEmail")
+          echo "Courier API response code: $status_code"
+
+          # Inspect response for errors
+          if [ "$status_code" -ne 200 ]; then
+            echo "Error: Email sending failed. Response:"
+            cat responseemail.json
+            exit 1
+          else
+            echo "Email sent successfully!"
+          fi
